# Nordics Company Digital Performance Analytics Pipeline
# A dbt project analyzing Nordics company digital performance using Crunchbase and SimilarWeb data

name: 'company_data_pipeline'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project
profile: 'company_data_pipeline'

# These configurations specify where dbt should look for different types of files
model-paths: ["models"]
analysis-paths: ["analyses"] 
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

# Directory which will store compiled SQL files
target-path: "target"

# Directories to be removed by `dbt clean`
clean-targets:
  - "target"
  - "dbt_packages"

# Model configurations organized by layer
models:
  company_data_pipeline:
    
    # STAGING LAYER
    # Purpose: Clean, standardize, and document raw source data
    # Materialization: Views (lightweight, always fresh)
    staging:
      +materialized: view
      +docs:
        node_color: "lightblue"
      crunchbase:
        +description: "Staging models for Crunchbase organization data with basic cleaning and standardization"
      similarweb:
        +description: "Staging models for SimilarWeb traffic data with quality filters and standardization"
    
    # INTERMEDIATE LAYER  
    # Purpose: Business logic, joins, and calculated fields
    # Materialization: Tables (better performance for complex transformations)
    intermediate:
      +materialized: table
      +docs:
        node_color: "orange"
      +description: "Intermediate models with enhanced business logic and entity relationships"
      
      # Enhanced models with additional calculated fields
      int_organizations_enhanced:
        +description: "Enhanced organization data with geographic standardization and role parsing"
        
      int_web_traffic_enhanced:
        +materialized: incremental
        +unique_key: 'web_traffic_id'
        +on_schema_change: 'fail'
        +incremental_strategy: 'merge'
        +description: "Enhanced web traffic data with quality scoring and platform analysis"
        
      int_company_web_bridge:
        +description: "Bridge table matching companies with their web traffic data"
    
    # MARTS LAYER
    # Purpose: Final analytical models for business users
    # Materialization: Tables (optimized for querying)
    marts:
      +materialized: table
      +docs:
        node_color: "green"
      +description: "Final analytical models ready for business intelligence and reporting"
      
      # Core analytical marts
      mart_company_digital_performance:
        +description: "Comprehensive company digital performance metrics aggregated across time"
        
      mart_company_digital_performance_timeseries:
        +description: "Time series analysis of company digital performance growth and trends"
        
      mart_category_insights:
        +description: "Industry category-level insights and benchmarking analysis"